### ISSUE TITLE
Cannot Access new Scrypted directory to Restore Configuration on HAOS

### ISSUE THREAD

**Issue by Daneish** [aegjoyce/ha-addons#10]
After updating to `v0.0.180` the Scrypted management console appeared as a fresh install requesting setup of new account with no previous configuration found. 

I can see the request to update the Scrypted directory in #9 and was change in 7f678837ca9f66a56d81f1ccb1e6d4b34d2535c2. 

Using the VScode Add On or connecting to my home assistant via SMB, I can see my old scrypted configuration saved in `\config\scrypted`, but I can’t see the new directory in order to restore my configuration. 

The `/data`, `/addons` and `/mnt` directories all appear empty.

Looking at [this forum topic](https://community.home-assistant.io/t/addons-config-data-folders-just-missing/336070) it appears that addon containers are not accessible when using HAOS.

I’m a noob when it comes to linux file systems, so I might be missing something obvious. Is there another way to access the addon’s directory to restore my configuration on HAOS?

I’m running:
Scrypted Addon v0.0.180
Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Raspberry Pi 4b

Thanks for reading, and for making this useful add on, very much appreciated!

**Comment by aegjoyce** [comment]
Hi - apologies, it was unfortunately a necessary change to allow users to back up Scrypted separately from the rest of Home Assistant due to large database sizes.

If you want a way to restore your old setup you could try the following:

1. Settings - System - Backups - Create Backup - Partial Backup
2. Select Scrypted (only) and Create
3. Download the newly made backup and open it on your computer
4. Copy everything that was in your `\config\scrypted` folder into `[backup name]\scrypted\data\scrypted_data`
5. Zip `[backup name]\scrypted` back up into a .tar.gz file
6. Zip the whole backup folder back up into a .tar.gz file
7. On Home Assistant, delete the backup you made, then upload your modified backup file and restore it

Hopefully this should work for you - could you let me know the outcome?

**Comment by PopNFreshIsMe** [comment]
I had this issue as well and by following these steps, I was able to restore everything to the updated version. Thanks!

**Comment by Daneish** [comment]
Thanks very much for the resolution, I never would have thought of that! Sorry it took me a while to get back to you, I had been away from my PC, then I was getting an error trying to upload the modified backup file: `400 Bad Request`.

It seemed to be due to the backup file having /./ directories within it, but Windows would not let me create those directories. Eventually I figured out I could drag files into the existing backup file in 7Zip, and that allowed me to upload the backup file and restore from it. After restarting Scrypted, my configuration has been restored. 

Thanks again for the speedy resolution!

**Comment by moto3001** [comment]
I can't seem to get it to restore with my previous plugins still.  I've tried it several times and have successfully copied the contents of the scrypted folder in \config to the .tar.gz of the both an older scrypted back and a new fresh scrypted backup, but neither seems to restore with my plugins.  I can see in the backup.tar file that the plugins are there in the plugins folder of scrypted, but even after multiple restores/restarts, it's always a fresh installation.
