### ISSUE TITLE
Port conflicts

### ISSUE THREAD

**Issue by danielcbaldwin** [aegjoyce/ha-addons#46]
Recent changes to specifically expose port 80 are conflicting with Nginx Proxy Manager which is also blunt on port 80. Would be great if a config was exposed that would allow us to change the host port on the container. 

Currently the add-on will not start for me because of this conflict.

**Comment by thstorm** [comment]
Same here, scrypted not starting because of Port Conflict:

Log:

`**2023/01/29 21:26:35 [emerg] 260#260: bind() to 172.30.32.1:80 failed (98: Address already in use)
nginx: [emerg] bind() to 172.30.32.1:80 failed (98: Address already in use)**
Removed Recordings: 0: 0 bytes.
Retained Recordings: 0: 0 bytes.
i OpenCV Motion Detection loaded @scrypted/opencv
Mixin provider 27 can no longer mixin 28. { mixinProvider: true, interfaces: false }
Mixin provider 27 can not mixin 28. It is no longer a MixinProvider. This may be temporary. Passing through.
i Haustür motionDetected: false (mixin)
**2023/01/29 21:26:35 [emerg] 260#260: bind() to 172.30.32.1:80 failed (98: Address already in use)
nginx: [emerg] bind() to 172.30.32.1:80 failed (98: Address already in use)
2023/01/29 21:26:35 [emerg] 260#260: still could not bind()
nginx: [emerg] still could not bind()**
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[Haustür] HomeKit Connection ::ffff:192.168.3.77
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by aegjoyce** [comment]
Should be fixed by v0.6.10-2, please report if does not resolve

**Comment by thstorm** [comment]
Thank you, working again!
